services:
  - type: web
    name: exort-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: MIMO_API_KEY
        sync: false
      - key: CEREBRAS_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DEFAULT_MODEL
        value: "google/gemma-4-26b-a4b-it:free"
      - key: PORT
        value: "8080"
